#!/bin/bash

# Add command to run your program here
echo "Hello World"

def print_type_a(array):
    print(str(opcode[array[0]]) + "00" + str(reg[array[1]]) + str(reg[array[2]]) + str(reg[array[3]]))


def print_type_b(array):
    print(str(opcode[array[0]]) + str(reg[array[1]]) + str(format(array[2], '08b')))
